name: nmsc
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda
  - ipykernel
  - ipython
  - jupyter
  - notebook
  - packaging
  - pip
  - python=3.10.14
  - pip:
      - absl-py==2.2.1
      - accelerate==1.5.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - autograd==1.7.0
      - autograd-gamma==0.5.0
      - autopep8==2.3.2
      - braceexpand==0.1.7
      - cfgv==3.4.0
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - distlib==0.3.9
      - docker-pycreds==0.4.0
      - ecos==2.0.14
      - einops==0.8.1
      - environs==14.1.1
      - fairscale==0.4.13
      - flash-attn==2.7.4.post1
      - fonttools==4.56.0
      - formulaic==1.1.1
      - fsspec==2025.3.0
      - fvcore==0.1.5.post20221221
      - geojson==3.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.71.0
      - h5py==3.13.0
      - huggingface-hub==0.29.3
      - identify==2.6.9
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - interface-meta==1.3.0
      - iopath==0.1.10
      - isort==6.0.1
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonpickle==4.0.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lifelines==0.30.0
      - lightning-utilities==0.14.2
      - llvmlite==0.44.0
      - markdown==3.7
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - monai==1.4.0
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - nbqa==1.9.1
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nodeenv==1.9.1
      - numba==0.61.0
      - numexpr==2.10.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openslide-python==1.4.1
      - osqp==0.6.7.post3
      - pandas==2.2.3
      - pillow==11.1.0
      - portalocker==3.1.1
      - pre-commit==4.2.0
      - protobuf==5.29.4
      - pycodestyle==2.12.1
      - pydantic==2.11.0
      - pydantic-core==2.33.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pyre-extensions==0.0.32
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyvis==0.3.2
      - pyyaml==6.0.2
      - qdldl==0.1.7.post5
      - regex==2024.11.6
      - requests==2.32.3
      - sacremoses==0.1.1
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scikit-survival==0.24.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentry-sdk==2.24.1
      - setproctitle==1.3.5
      - shapely==2.0.7
      - smmap==5.0.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.13
      - timm==1.0.15
      - tokenize-rt==6.1.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.6.0
      - torchmetrics==1.7.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.50.2
      - triton==3.2.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - umap-learn==0.5.7
      - urllib3==2.3.0
      - virtualenv==20.29.3
      - wandb==0.19.8
      - webdataset==0.2.111
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.29.post3
      - xgboost==3.0.0
      - yacs==0.1.8
